# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9387c056aac15d8e4758a6620f62737df4c225c4f4863837e251b85238a2189cfe2ef5939a539e5b3721f2ed635c62b45c86f1f04e55ecee0bed36ade8e46ff

test:
  secret_key_base: d8c85e32a259d22b540e3a58941d53adc5b3dedd41496b3512ccb4ba2f1d0184829336418d3b3073bc4c326a3c4b1e3ecd8b428432e044c2b83dc028f7ff9245

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
